USE [master]
GO

/****** Object:  Database [DevOps]    Script Date: 2/15/2017 4:59:39 PM ******/
CREATE DATABASE [DevOps]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DevOps', FILENAME = N'D:\MSSQL\Data\DevOps.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DevOps_log', FILENAME = N'D:\MSSQL\Log\DevOps_log.ldf' , SIZE = 4224KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DevOps] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DevOps].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DevOps] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DevOps] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DevOps] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DevOps] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DevOps] SET ARITHABORT OFF 
GO

ALTER DATABASE [DevOps] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DevOps] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DevOps] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DevOps] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DevOps] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [DevOps] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DevOps] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DevOps] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DevOps] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DevOps] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DevOps] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DevOps] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DevOps] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DevOps] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DevOps] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DevOps] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DevOps] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DevOps] SET RECOVERY FULL 
GO

ALTER DATABASE [DevOps] SET  MULTI_USER 
GO

ALTER DATABASE [DevOps] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DevOps] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DevOps] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DevOps] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DevOps] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DevOps] SET  READ_WRITE 
GO


