//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataModel.DevOps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigVariableValue
    {
        public int id { get; set; }
        public int configvar_id { get; set; }
        public string environment_type { get; set; }
        public string value { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modify_date { get; set; }
        public Nullable<System.DateTime> published_date { get; set; }
        public bool published { get; set; }
    
        public virtual Enum_EnvironmentType Enum_EnvironmentType { get; set; }
        public virtual ConfigVariable ConfigVariable { get; set; }
    }
}
