//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataModel.DevOps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevOpsEntities : DbContext
    {
        public DevOpsEntities()
            : base("name=DevOpsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<ConfigFileAttribute> ConfigFileAttributes { get; set; }
        public virtual DbSet<ConfigFileElement> ConfigFileElements { get; set; }
        public virtual DbSet<ConfigVariableValue> ConfigVariableValues { get; set; }
        public virtual DbSet<Enum_EnvironmentType> Enum_EnvironmentType { get; set; }
        public virtual DbSet<Enum_EnvironmentVariableType> Enum_EnvironmentVariableType { get; set; }
        public virtual DbSet<Enum_Locations> Enum_Locations { get; set; }
        public virtual DbSet<EnvironmentVariable> EnvironmentVariables { get; set; }
        public virtual DbSet<MachineComponentPathMap> MachineComponentPathMaps { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<ServerGroup> ServerGroups { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<ExecutionHistory> ExecutionHistories { get; set; }
        public virtual DbSet<Script> Scripts { get; set; }
        public virtual DbSet<vi_ConfigVariables> vi_ConfigVariables { get; set; }
        public virtual DbSet<ConfigVariable> ConfigVariables { get; set; }
        public virtual DbSet<ConfigFile> ConfigFiles { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
    }
}
