//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataModel.DevOps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionHistory
    {
        public int id { get; set; }
        public int script_id { get; set; }
        public string script_name { get; set; }
        public string user_name { get; set; }
        public System.DateTime execution_dt { get; set; }
        public bool contains_errors { get; set; }
        public string output { get; set; }
    
        public virtual Script Script { get; set; }
    }
}
