//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataModel.DevOps
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineApplicationMap
    {
        public int machine_id { get; set; }
        public Nullable<bool> active { get; set; }
        public int application_id { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
