//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataModel.DevOps
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineComponentPath
    {
        public int machine_id { get; set; }
        public int component_id { get; set; }
        public string config_path { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
